### ISSUE TITLE
Make the 'rxmongo.messages' package available.

### ISSUE THREAD

**Issue by francescoditrani** [reactific/RxMongo#2]
The 'rxmongo.messages' package is not included in the 0.1-SNAPSHOT version of rxmongo-client.

**Comment by reid-spencer** [comment]
The package is here: https://github.com/reactific/RxMongo/tree/master/messages

**Comment by reid-spencer** [comment]
I have checked in minor changes, run full tests, verified on Travis and re-pushed the 0.1.0-SNAPSHOT. 
All the packages are now reachable on SonaType here:

https://oss.sonatype.org/content/repositories/snapshots/com/reactific/
